# Generated by Django 5.2.8 on 2025-11-30 17:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модулі'},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Загальна тривалість курсу в годинах', verbose_name='Тривалість (годин)'),
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, help_text='Залиште порожнім для необмеженої кількості', null=True, verbose_name='Максимум студентів'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = безкоштовно', max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(verbose_name='Зміст'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Залиште порожнім для загального оголошення', null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('general', 'Загальне'), ('important', 'Важливе'), ('update', 'Оновлення')], default='general', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Початковий'), ('intermediate', 'Середній'), ('advanced', 'Просунутий')], default='beginner', max_length=20, verbose_name='Рівень складності'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогрес (%)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
    ]
