# Generated by Django 5.2.8 on 2025-12-10 21:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0003_announcement_updated_at_enrollment_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Завдання', 'verbose_name_plural': 'Завдання'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='allow_late_submission',
            field=models.BooleanField(default=True, verbose_name='Дозволити здачу після дедлайну'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Текст'), ('file', 'Файл'), ('both', 'Текст + Файл')], default='both', max_length=20, verbose_name='Тип здачі'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Максимальний бал'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_id',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID сертифіката'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Відгук'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Бал'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grades_given', to=settings.AUTH_USER_MODEL, verbose_name='Викладач'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст відповіді'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'zip', 'jpg', 'jpeg', 'png'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'На перевірці'), ('graded', 'Оцінено'), ('returned', 'Повернуто на доопрацювання')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
