# Generated by Django 5.2.8 on 2025-12-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='final_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Підсумкова оцінка'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='PDF файл'),
        ),
    ]
