# Generated by Django 5.2.8 on 2025-11-22 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва уроку')),
                ('content', models.TextField(verbose_name='Текстовий контент')),
                ('video_url', models.URLField(blank=True, help_text='Посилання на YouTube або інше відео', verbose_name='Посилання на відео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Тривалість (хвилин)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опублікований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='Модуль')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'order')},
            },
        ),
        migrations.CreateModel(
            name='LessonMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lessons/media/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Зображення'), ('video', 'Відео'), ('document', 'Документ')], max_length=10, verbose_name='Тип файлу')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата завантаження')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='lessons.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Медіафайл уроку',
                'verbose_name_plural': 'Медіафайли уроків',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
