# Generated by Django 5.2.8 on 2025-12-05 20:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_module_options_alter_module_unique_together_and_more'),
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='lessonmedia',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Медіафайл уроку', 'verbose_name_plural': 'Медіафайли уроків'},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Дозволити перегляд без запису на курс', verbose_name='Безкоштовний перегляд'),
        ),
        migrations.AddField(
            model_name='lessonmedia',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Розмір файлу (bytes)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(help_text='Текстовий опис уроку', verbose_name='Зміст уроку'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Тривалість (хвилин)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.module', verbose_name='Модуль'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Посилання на YouTube відео', null=True, verbose_name='YouTube відео'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='file',
            field=models.FileField(upload_to='lessons/media/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'avi', 'zip'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='file_type',
            field=models.CharField(choices=[('image', 'Зображення'), ('document', 'Документ'), ('video', 'Відео'), ('other', 'Інше')], default='document', max_length=20, verbose_name='Тип файлу'),
        ),
        migrations.AlterField(
            model_name='lessonmedia',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Назва файлу'),
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('time_spent', models.PositiveIntegerField(default=0, verbose_name='Час перегляду (секунд)')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогрес уроку',
                'verbose_name_plural': 'Прогрес уроків',
                'unique_together': {('lesson', 'student')},
            },
        ),
    ]
